name: "run-black-pr-action"
description: "run black inside a github workflow and create PR"
inputs:
  head_branch:  # path
    description: 'The branch to rebase and latest changes from'
    required: true
    default: 'master'
runs:
    using: composite
    steps:
    - run: pip3 install setuptools wheel
      shell: bash
    - run: pip3 install black
      shell: bash
    - run: |
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      shell: bash
    #- run: echo "NOW=$(date +'%Y-%m-%dT%H')" >> $GITHUB_ENV
    - run: echo "NOW=$(date)" >> $GITHUB_ENV
      shell: bash
    - run: git branch black-pr-bot-v1
      shell: bash
    - run: git checkout black-pr-bot-v1
      shell: bash
    - run: git switch -C main origin/black-pr-bot-v1
      shell: bash
    - run: python3 -m black .
      shell: bash
    - run: git add . && git commit -m "black-auto-format-bot"
      shell: bash
    - run: git push -u origin black-pr-bot-v1
      shell: bash
    - run: gh pr create --title "[run-black-pr-action bot] Black Formatting" --body "These are changes created by running black on you repository" --head black-pr-bot-v1
      shell: bash
