name: test-action

on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run my action
        uses: raiyanyahya/run-black-pr-action@v1.0.2