name: test-black-pr-action

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  test-black-pr-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run black and create a pr
        uses: raiyanyahya/run-black-pr-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}